version: '3.9'

services:
  web:
    image: site_vizit:latest  # Указывает название и тег образа
    build:
      context: .  # Путь к Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile, если оно отличается от стандартного
    container_name: site_vizit_container  # Имя контейнера
    ports:
      - "8501:8501"
    restart: unless-stopped